# Generated by Django 5.2.3 on 2025-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_remove_employee_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('coming', 'Coming'), ('going', 'Going')], default='coming', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date', 'status')},
        ),
    ]
