# Generated by Django 5.2.3 on 2025-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_attendance_unique_together_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_faces/'),
        ),
    ]
