# Generated by Django 5.2.3 on 2025-07-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='assigned_categories',
            field=models.ManyToManyField(blank=True, to='core.jobcategory'),
        ),
    ]
