# Generated by Django 5.2.3 on 2025-07-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_supervisor_assigned_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='assigned_categories',
        ),
    ]
